Update CONTRIBUTING.md
facebookresearch/NeuralCompression pull request #17
Opened 2021-09-23 21:31 UTC by 0x00b1

2021-09-24 17:29 UTC, mmuckley requested changes
A few minor comments to clarify what the code is doing.

2021-09-24 17:29 UTC, mmuckley commented on .github/CONTRIBUTING.md
> +
```suggestion

Using `pip`, you can install the package in development mode by running:

```

2021-09-24 17:29 UTC, mmuckley commented on .github/CONTRIBUTING.md
> +
```suggestion

We test the package using `pytest`, which you can run locally by typing

```

2021-09-25 21:33 UTC, 0x00b1 commented
Lovely! Accepted both!

2021-09-27 14:58 UTC, mmuckley approved these changes
LGTM.

2021-09-27 14:59 UTC, merged