HiFiC modules
facebookresearch/NeuralCompression pull request #21
Opened 2021-09-28 22:17 UTC by 0x00b1

Implements the following modules from Mentzer, et al. (2020)

- HiFiCDiscriminator
- HiFiCEncoder
- HiFiCGenerator

```bibtex
@misc{mentzer2020highfidelity,
      title={High-Fidelity Generative Image Compression}, 
      author={Fabian Mentzer and George Toderici and Michael Tschannen and Eirikur Agustsson},
      year={2020},
      eprint={2006.09965},
      archivePrefix={arXiv},
      primaryClass={eess.IV}
}
```

2021-09-29 21:16 UTC, 0x00b1 commented
I'm not sure how to deal with the MyPy `kwargs` issue without inlining. @mmuckley Any suggestions?

2021-09-30 01:28 UTC, mmuckley commented
Hello @0x00b1, I'm not sure it's that easy as `**kwargs` could have essentially any type. That being said I think I agree with `mypy` - `**kwargs` can pass on essentially anything and as such can be a breeding ground for bugs. My suggestion would be to just fully specify all `kwargs` and let users subclass and extend the models when needed to pass new parameters.

Note that this is primarily due to the code being in the core repository - if it were under `projects` then I would say we can adopt a soft linting standard and you could just disable `mypy` for your folder.

2021-09-30 20:30 UTC, mmuckley reviewed
Making some recommendations to pass the lints easier - I think it's great to use `torch.nn.Sequential` and loops to organize things. There shouldn't be any compute cost - these are just in `__init__` and the loops are tiny.

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_channel_norm_2d.py
> +    input_channels, momentum=0.1, affine=True, track_running_stats=False, **kwargs
`**kwargs` unused here.

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_channel_norm_2d.py
> +        self, input_channels, momentum=0.1, epsilon=1e-3, affine=True, **kwargs
`**kwargs` unused here.

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_discriminator.py
> +        return torch.sigmoid(predictions), predictions
Proposing a `mypy`-friendly version.
```suggestion
        self.input_sequence = torch.nn.Sequential(
            torch.nn.LeakyReLU(0.2),
            torch.nn.Conv2d(
                self.features, 12, (3, 3), padding=1, padding_mode="reflect"
            ),
            torch.nn.Upsample(None, 16, "nearest"),
        )

        filters = (64, 128, 256, 512)

        conv_sequence = []
        old_size = self.image_dimensions[0] + 12
        for current_filter in filters:
            conv_sequence.append(
                torch.nn.utils.spectral_norm(
                    torch.nn.Conv2d(
                        old_size,
                        current_filter,
                        (4, 4),
                        padding=1,
                        padding_mode="reflect",
                        stride=2,
                    )
                )
            )
            old_size = current_filter

        conv_sequence.append(torch.nn.Conv2d(filters[3], 1, (1, 1), (1, 1)))

        self.conv_sequence = torch.nn.Sequential(*conv_sequence)

    def forward(
        self, x: torch.Tensor, y: torch.Tensor
    ) -> typing.Tuple[torch.Tensor, torch.Tensor]:
        predictions = self.conv_sequence(
            torch.cat((x, self.input_sequence(y)), 1)
        ).view(-1, 1)

        return torch.sigmoid(predictions), predictions
```

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_encoder.py
> +class HiFiCEncoder(torch.nn.Module):
Same as above - I think we can avoid any use of `kwargs` with loops and `torch.nn.Sequential`.

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_generator.py
> +class _ResidualBlock(torch.nn.Module):
See above on `Sequential`.

2021-09-30 20:30 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_generator.py
> +class HiFiCGenerator(torch.nn.Module):
See above on `Sequential`

2021-09-30 21:45 UTC, 0x00b1 commented
@mmuckley Thanks! I love the changes.

2021-10-01 15:17 UTC, mmuckley requested changes

2021-10-01 15:17 UTC, mmuckley commented on neuralcompression/models/_hific/__init__.py
> +from ._hific_discriminator import HiFiCDiscriminator
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on neuralcompression/models/_hific/_channel_norm_2d.py
> +import torch
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_discriminator.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_encoder.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on neuralcompression/models/_hific/_hific_generator.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on tests/models/_hific/test_hific_discriminator.py
> +import torch
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:17 UTC, mmuckley commented on tests/models/_hific/test_hific_generator.py
> +import torch
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-02 01:12 UTC, mmuckley approved these changes
LGTM.

2021-10-04 15:51 UTC, merged