HiFiC adversarial losses
facebookresearch/NeuralCompression pull request #23
Opened 2021-09-29 16:57 UTC by 0x00b1

- non-saturating adversarial loss

2021-09-30 17:18 UTC, 0x00b1 commented
@mmuckley The two adversarial losses used in the HiFiC paper. I have mixed feelings about this PR. They are, of course, useful and certainly useful beyond a HiFiC implementation but I think they are out of scope for this package. Unfortunately, I don't know if there's a better place for them and I'm uncertain about the roadmap (if one exists) for general-purpose adversarial functionality in PyTorch. I suppose an alternative option worthy of consideration is moving them into `neuralcompression.models` and making them private, restricting their use to the HiFiC implementation.

2021-09-30 17:35 UTC, mmuckley commented
@0x00b1 I think it makes perfect sense to make them private to HiFiC at the moment since it's just one model. If we have multiple models with discriminator losses then we can look at how to harmonize them.

2021-09-30 17:39 UTC, 0x00b1 commented
@mmuckley Great! I’ll go ahead and make those changes.

2021-09-30 20:02 UTC, mmuckley approved these changes
LGTM, although I couldn't find where they mention the least squares adversarial loss in the paper. Let me know if you want me to merge as-is.

2021-10-01 15:16 UTC, mmuckley requested changes

2021-10-01 15:16 UTC, mmuckley commented on neuralcompression/models/_hific/_least_squares_adversarial_loss.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:16 UTC, mmuckley commented on neuralcompression/models/_hific/_non_saturating_adversarial_loss.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 20:41 UTC, merged