estimate tails
facebookresearch/NeuralCompression pull request #25
Opened 2021-09-29 22:19 UTC by 0x00b1

2021-09-30 01:34 UTC, mmuckley requested changes

2021-09-30 01:34 UTC, mmuckley commented on neuralcompression/functional/_estimate_tails.py
> +) -> torch.Tensor:
Primary ask is a docstring here describing what the function is doing mathematically - even if it's for internal use.

2021-09-30 17:11 UTC, 0x00b1 commented
@mmuckley part of the complement of useful, general-purpose ops from Ballé (2018). I'll make a follow-up PR for boundary ops that uses this implementation.

2021-09-30 17:37 UTC, mmuckley commented
None of the major powers are watching this repository (yet) so I think the war will hold off for now.

2021-09-30 20:12 UTC, mmuckley commented
For this one I'm just waiting on a unit test.

2021-09-30 22:08 UTC, mmuckley approved these changes
LGTM.

2021-10-01 15:15 UTC, mmuckley requested changes

2021-10-01 15:15 UTC, mmuckley commented on neuralcompression/functional/_estimate_tails.py
> +import typing
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 15:15 UTC, mmuckley commented on tests/functional/test_estimate_tails.py
> +import math
Please add a copyright header.
```
"""
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
"""
```

2021-10-01 16:29 UTC, mmuckley approved these changes
LGTM.

2021-10-01 18:30 UTC, merged